[tool.poetry]
name = "003-streamlit-split-and-summarize"
version = "0.1.0"
description = "App de resumen de textos largos con AI"
authors = ["julio colomer <info@aiaccelera.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
streamlit = "^1.37.0"
langchain = "^1.0.5"
openai = "^2.7.1"
tiktoken = "^0.12.0"
aiohttp = "^3.8.5"
pandas = "^2.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

