[tool.poetry]
name = "003_streamlit_split_and_summarize"
version = "1.0.0"
description = "AI app to summarize long texts with LangChain"
authors = ["Tu Nombre <tu@email.com>"]
readme = "README.md"
packages = [{include = "*"}]

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "1.37.0"
rich = "14.2.0"
langchain = "1.0.5"
openai = "2.7.1"
langchain-openai = "0.0.8"
tiktoken = "0.12.0"
aiohttp = "3.8.5"
numpy = "1.26.0"
pandas = "2.1.1"
regex = "2023.10.22"
tenacity = "8.2.2"
requests = "2.31.0"
urllib3 = "2.5.0"
toolz = "1.1.0"
toml = "0.10.2"
typing-extensions = "4.15.0"
markupsafe = "3.0.3"
tzdata = "2025.2"
sqlalchemy = "2.0.44"

[build-system]
requires = ["poetry-core>=1.3.0"]
build-backend = "poetry.core.masonry.api"
