[tool.poetry]
name = "003-streamlit-split-and-summarize"
version = "0.1.0"
description = "AI app to summarize long text files using OpenAI and LangChain"
authors = ["Julio Colomer <info@aiaccelera.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
streamlit = "^1.37.0"
langchain = "^1.0.5"
openai = "^2.7.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

